### ISSUE TITLE
feat: deploy backend in systemd using pm2

### ISSUE THREAD

**Issue by refigo** [42Mogle/42-mogle-backend#47]
### 백엔드 프로세스를 백그라운드에 알아서 실행하도록 설정하기

1. Intall `PM2`
	-  `npm install pm2@latest -g`
2. Build project
	- `npm run build`
3. Run project
	- `pm2 start dist/main.js --name <application_name>`
4. Set application auto restart after system reboot
	- `pm2 startup systemd`
	- `pm2 save`

이제 우리 백엔드 혼자 알아서 잘 살아갈겁니다.

- reference link
	- Deploy Nest JS App using PM2 on Linux (Ubuntu) Server
		- https://dev.to/deadwin19/deploy-nest-js-app-using-pm2-on-linux-ubuntu-server-88f

**Comment by Han-Joon-Hyeok** [comment]
He is god
